name: Run Tests and Generate coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Clean Coverage Directory
        run: rm -rf ./coverage

      - name:Override gitignore for coverage
        run: |
            echo "!/coverage" >> .gitignore
            git add .gitignore

      - name: Run dashboard Jest tests
        run: npx nx run dashboard:test --codeCoverage=true --no-cache --skip-nx-cache

      - name: Run shellapp Jest tests
        run: npx nx run dashboard:test --codeCoverage=true --no-cache --skip-nx-cache

      - name: Run shellapp2 Jest tests
        run: npx nx run dashboard:test --codeCoverage=true --no-cache --skip-nx-cache