name: Run Tests and Generate coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Jest tests
        run: npx nx test dashboard --code-coverage
             npx nx test shellapp --code-coverage
             npx nx test shellapp2 --code-coverage
